constellationcollector_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # Static Routes
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    # Constellation Routes
    path('constellations/', views.constellations_index, name='constellations_index'),
    path('constellations/new/', views.add_constellation, name='add_constellation'),
    path('constellations/<int:constellation_id>/delete/', views.delete_constellation, name='delete_constellation'),
    path('constellations/<int:constellation_id>/', views.constellations_detail, name='detail'),
    path('constellations/<int:constellation_id>/edit/', views.edit_constellation, name='edit_constellation'),
    # Stars
    path('constellations/<int:constellation_id>/add_star/', views.add_star, name='add_star'),
    # Planets
    path('constellations/<int:constellation_id>/assoc_planet/<int:planet_id>/', views.assoc_planet, name='assoc_planet'),
    path('constellations/<int:constellation_id>/dissociate_planet/<int:planet_id>/', views.dissociate_planet, name='dissociate_planet'),
    # Auth
    path('accounts/signup', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Planet(models.Model):
    name = models.CharField(max_length=20)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Constellation(models.Model):
    name = models.CharField(max_length=50)
    date_observed = models.DateField()
    symbolism = models.TextField(max_length=200)
    num_main_stars = models.IntegerField()
    brightest_star = models.CharField(max_length=50) 
    planets = models.ManyToManyField(Planet)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Star(models.Model):
    name = models.CharField(max_length=50)
    apparent_magnitude = models.DecimalField(max_digits=2, decimal_places=1)


    constellation = models.ForeignKey(Constellation, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

main_app/forms.py
from django import forms
from .models import Star, Constellation

class StarForm(forms.ModelForm):
  class Meta:
    model = Star
    fields = ('name', 'apparent_magnitude')

class ConstellationForm(forms.ModelForm):
  class Meta:
    model = Constellation
    fields = ('name', 'symbolism', 'num_main_stars', 'brightest_star', 'date_observed')

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Constellation, Planet
from .forms import StarForm, ConstellationForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required


# --------------------------------------- STATIC PAGES
def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


# --------------------------------------- CONSTELLATIONS
@login_required
def constellations_index(request):
    constellations = Constellation.objects.filter(user=request.user)
    return render(request, 'constellations/index.html', {'constellations': constellations })


@login_required
def constellations_detail(request, constellation_id):
    constellation = Constellation.objects.get(id=constellation_id)
    planets_constellation_doesnt_have = Planet.objects.exclude(id__in = constellation.planets.all().values_list('id'))
    star_form = StarForm()
    context = {
        'constellation': constellation, 
        'star_form': star_form,
        'planets': planets_constellation_doesnt_have
        }
    return render(request, 'constellations/detail.html', context)


@login_required
def add_constellation(request):
    if request.method == 'POST':
        constellation_form = ConstellationForm(request.POST)
        if constellation_form.is_valid():
            new_constellation = constellation_form.save(commit=False)
            new_constellation.user = request.user
            new_constellation.save()
            return redirect('detail', new_constellation.id)
    else: 
        form = ConstellationForm()
        context = {'form': form}
        return render(request, 'constellations/new.html', context)


@login_required
def edit_constellation(request, constellation_id):
    constellation = Constellation.objects.get(id=constellation_id)
    if request.method == 'POST':
        constellation_form = ConstellationForm(request.POST, instance=constellation)
        if constellation_form.is_valid():
            updated_constellation = constellation_form.save()
            return redirect('detail', updated_constellation.id)
    else: 
        form = ConstellationForm(instance=constellation)
        context = {'form': form}
        return render(request, 'constellations/edit.html', context)


@login_required
def delete_constellation(request, constellation_id):
    Constellation.objects.get(id=constellation_id).delete()
    return redirect('constellations_index')


# --------------------------------------- CONSTELLATION STARS
@login_required
def add_star(request, constellation_id):
    form = StarForm(request.POST)
    if form.is_valid():
        new_star = form.save(commit=False)
        new_star.constellation_id = constellation_id
        new_star.save()
    return redirect('detail', constellation_id=constellation_id)


# --------------------------------------- CONSTELLATION PLANETS
@login_required
def assoc_planet(request, constellation_id, planet_id):
    planet = Planet.objects.get(id=planet_id)
    Constellation.objects.get(id=constellation_id).planets.add(planet)
    return redirect('detail', constellation_id)


@login_required
def dissociate_planet(request, constellation_id, planet_id):
    planet = Planet.objects.get(id=planet_id)
    Constellation.objects.get(id=constellation_id).planets.remove(planet)
    return redirect('detail', constellation_id)


# --------------------------------------- AUTH
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('constellations_index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block title %}
About
{% endblock %}

{% block content %}
<h1>About Constellation Collector</h1>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title> Constellation Collector - 
    {% block title %} 
    {% endblock %}
  </title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Constellation Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'add_constellation' %}">Add Constellation</a></li>
          <li><a href="{% url 'constellations_index' %}">My Constellations</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2020 Constellation Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/constellations/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Constellation Details</h1>

<div class="row">
  <div class="col s8">
    <div class="card">
      <div class="card-content">
        <table>
          <thead>
            <tr>
              <th>{{ constellation.name }}</th>
              <th class="right-align">
                Date Observed: {{ constellation.date_observed }}
              </th>
            </tr>
          </thead>
        </table>
        <br />
        <p>Symbolism: {{ constellation.symbolism }}</p>
        <br />
        <p>Number of Main Stars: {{ constellation.num_main_stars }}</p>
        <br />
        <p>Brightest Star: {{ constellation.brightest_star }}</p>
      </div>
      {% if constellation.user.id == user.id %}
        <div class="card-action">
          <a href="{% url 'edit_constellation' constellation.id %}"
            type="submit"
            class="btn-small">Edit</a>
          <a href="{% url 'delete_constellation' constellation.id %}"
            type="submit"
            class="btn-small red">Delete</a>
        </div>
      {% endif %}
    </div>
  </div>
  <div class="col s4">
    <h4>Stars</h4>
    {% if constellation.user.id == user.id %}
      <form action="{% url 'add_star' constellation.id %}" method="POST">
        {% csrf_token %} {{ star_form.as_p }}
        <input type="submit" class="btn" value="Add Star" />
      </form>
    {% endif %}
    <table class="striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Apparent Magnitude</th>
        </tr>
      </thead>
      <tbody>
        {% for star in constellation.star_set.all %}
          <tr>
            <td>{{star.name}}</td>
            <td>{{star.apparent_magnitude}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr />
<div class="row">
  <div class="col s6">
    <h6>Planets aligning with {{ constellation.name }} on {{ constellation.date_observed }}:</h6>
    {% if constellation.planets.count %} 
      {% for planet in constellation.planets.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">{{ planet.name }}</span>
          </div>
          {% if constellation.user.id == user.id %}
          <div class="card-action">
            <form action="{% url 'dissociate_planet' constellation.id planet.id %}"
              method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
          {% endif %}
        </div>
      {% endfor %} 
    {% else %}
    <p>
      No planets could be seen in {{ constellation.name }} on {{ constellation.date_observed }}.
    </p>
    {% endif %}
  </div>

  {% if constellation.user.id == user.id %}
    <div class="col s6">
      <h6>Planets:</h6>
      {% if planets.count %} 
        {% for planet in planets.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">{{ planet.name }}</span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_planet' constellation.id planet.id %}"
              method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
        {% endfor %} 
      {% endif %}
    </div>
  {% endif %}
</div>
{% endblock %}

main_app/templates/constellations/edit.html
{% extends 'base.html' %}
{% block content %}

  <h1>Edit Constellation</h1>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn-small" type="submit">Update</button>
  </form>

{% endblock %}

main_app/templates/constellations/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Constellation List</h1>

{% for constellation in constellations %}
  <div class="card">
    <a href="{% url 'detail' constellation.id %}">
      <div class="card-content">
        <span class="card-title">{{ constellation.name }}</span>
        <p>Symbolism: {{ constellation.symbolism }}</p>
        <p>Number of Main Stars: {{ constellation.num_main_stars }}</p>
        <p>Brightest Star: {{ constellation.brightest_star }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/constellations/new.html
{% extends 'base.html' %}
{% block content %}

  <h1>Add A New Constellation</h1>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn-small" type="submit">Add Constellation</button>
  </form>
<script>
  const dateEl = document.getElementById('id_date_observed');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block title %}
Homepage
{% endblock %}

{% block content %}
<h1>Welcome to the Constellation Collector</h1>
{% endblock %}